apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: smrq8457i-java-quarkus-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/smrq8457i-java-quarkus